replicaCount: 2

image:
  repository: thanh5320/luklak-service-app
  tag: 7
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8888

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
